#!/bin/sh
#
# This launches pyFormex with the Python3 interpreter.
# The script is currently intended solely for development purposes
# and will not yield a usable program.
# Configuration is saved in the p2to3 development directory.
# Output is also logged there.
#
DIR=$(dirname $(readlink -f $0))
python3 $DIR/../pyformex/pyformex --config=$DIR/pyformex.conf --noredirect 2>&1 |tee $DIR/2to3.out

# End
