// Script generated by pyFormex 1.0.0~a1 (GL2) (release-0.9.1-378-gbd25a83)
var the_renderer;
var the_controls;

window.onload = function() {
showWebGL();
}

showWebGL = function() {
if (the_controls != null) the_controls.destroy();
if (the_renderer != null) the_renderer.destroy();
var r = new X.renderer3D();
the_renderer = r;
r.config.ORDERING_COMPARATOR = 'ID';
r.init();

r.setAlphablend(true);
var object_1_backfaces = new X.mesh();
object_1_backfaces.file = 'Combined_s0_object_1_backfaces.pgf';
object_1_backfaces.caption = 'A cone';
object_1_backfaces.color = [0.0, 0.0, 1.0];
object_1_backfaces.opacity = 1.0;
object_1_backfaces.lighting = true;
object_1_backfaces.cullface = 'front';
r.add(object_1_backfaces);

var object_1_frontfaces = new X.mesh();
object_1_frontfaces.file = 'Combined_s0_object_1_frontfaces.pgf';
object_1_frontfaces.caption = 'A cone';
object_1_frontfaces.color = [0.0, 0.0, 1.0];
object_1_frontfaces.opacity = 1.0;
object_1_frontfaces.lighting = true;
object_1_frontfaces.cullface = 'back';
r.add(object_1_frontfaces);

var object_1_faces = new X.mesh();
object_1_faces.children = new Array();
object_1_faces.children.push(object_1_frontfaces);
object_1_faces.children.push(object_1_backfaces);
object_1_faces.color = [0.0, 0.0, 1.0];
object_1_faces.opacity = 1.0;

var object_1 = new X.mesh();
object_1.children = new Array();
object_1.children.push(object_1_faces);


var object_2_backfaces = new X.mesh();
object_2_backfaces.file = 'Combined_s0_object_2_backfaces.pgf';
object_2_backfaces.caption = 'A cylinder';
object_2_backfaces.color = [1.0, 1.0, 0.0];
object_2_backfaces.opacity = 1.0;
object_2_backfaces.lighting = true;
object_2_backfaces.cullface = 'front';
r.add(object_2_backfaces);

var object_2_frontfaces = new X.mesh();
object_2_frontfaces.file = 'Combined_s0_object_2_frontfaces.pgf';
object_2_frontfaces.caption = 'A cylinder';
object_2_frontfaces.color = [1.0, 1.0, 0.0];
object_2_frontfaces.opacity = 1.0;
object_2_frontfaces.lighting = true;
object_2_frontfaces.cullface = 'back';
r.add(object_2_frontfaces);

var object_2_faces = new X.mesh();
object_2_faces.children = new Array();
object_2_faces.children.push(object_2_frontfaces);
object_2_faces.children.push(object_2_backfaces);
object_2_faces.color = [1.0, 1.0, 0.0];
object_2_faces.opacity = 1.0;

var object_2 = new X.mesh();
object_2.children = new Array();
object_2.children.push(object_2_faces);


var object_0_backfaces = new X.mesh();
object_0_backfaces.file = 'Combined_s0_object_0_backfaces.pgf';
object_0_backfaces.caption = 'A sphere';
object_0_backfaces.color = [1.0, 0.0, 0.0];
object_0_backfaces.opacity = 0.5;
object_0_backfaces.lighting = true;
object_0_backfaces.cullface = 'front';
r.add(object_0_backfaces);

var object_0_frontfaces = new X.mesh();
object_0_frontfaces.file = 'Combined_s0_object_0_frontfaces.pgf';
object_0_frontfaces.caption = 'A sphere';
object_0_frontfaces.color = [1.0, 0.0, 0.0];
object_0_frontfaces.opacity = 0.5;
object_0_frontfaces.lighting = true;
object_0_frontfaces.cullface = 'back';
r.add(object_0_frontfaces);

var object_0_faces = new X.mesh();
object_0_faces.children = new Array();
object_0_faces.children.push(object_0_frontfaces);
object_0_faces.children.push(object_0_backfaces);
object_0_faces.color = [1.0, 0.0, 0.0];
object_0_faces.opacity = 0.5;

var object_0 = new X.mesh();
object_0.children = new Array();
object_0.children.push(object_0_faces);


r.onShowtime = function() {
var gui = new dat.GUI();
the_controls = gui;
var gui_object_1 = gui.addFolder('A cone');
var gui_object_1_visible = gui_object_1.add(object_1,'visible').name('visible');
var gui_object_1_faceopacity = gui_object_1.add(object_1_faces,'opacity',0,1).name('face opacity');
var gui_object_1_facecolor = gui_object_1.addColor(object_1_faces,'color').name('face color');
var gui_object_2 = gui.addFolder('A cylinder');
var gui_object_2_visible = gui_object_2.add(object_2,'visible').name('visible');
var gui_object_2_faceopacity = gui_object_2.add(object_2_faces,'opacity',0,1).name('face opacity');
var gui_object_2_facecolor = gui_object_2.addColor(object_2_faces,'color').name('face color');
var gui_object_0 = gui.addFolder('A sphere');
var gui_object_0_visible = gui_object_0.add(object_0,'visible').name('visible');
var gui_object_0_faceopacity = gui_object_0.add(object_0_faces,'opacity',0,1).name('face opacity');
var gui_object_0_facecolor = gui_object_0.addColor(object_0_faces,'color').name('face color');

var gui_camera = gui.addFolder('Camera');
var gui_camera_reset = gui_camera.add(r.camera,'reset');

var gui_global = gui.addFolder('Global');
var gui_global_alphablend = gui_global.add(r,'toggleAlphablend');
}

r.camera.position = [5.9137648309002806, 0.0, 0.39999997615814098];
r.camera.focus = [0.0, 0.0, 0.39999998];
r.camera.up = [0.0, 1.0, 0.0];

r.render();
};

showBaumKuchen = function() {
if (the_controls != null) the_controls.destroy();
if (the_renderer != null) the_renderer.destroy();
var r = new X.renderer3D();
the_renderer = r;
r.config.ORDERING_COMPARATOR = 'ID';
r.init();

r.setAlphablend(false);
var object_3_wires = new X.mesh();
object_3_wires.file = 'Combined_s1_object_3_wires.pgf';
object_3_wires.color = [0.0, 0.0, 0.0];
object_3_wires.opacity = 0.5;
object_3_wires.lighting = false;
r.add(object_3_wires);

var object_3_backfaces = new X.mesh();
object_3_backfaces.file = 'Combined_s1_object_3_backfaces.pgf';
object_3_backfaces.color = [0.0, 0.0, 0.0];
object_3_backfaces.opacity = 0.5;
object_3_backfaces.lighting = true;
object_3_backfaces.cullface = 'front';
r.add(object_3_backfaces);

var object_3_frontfaces = new X.mesh();
object_3_frontfaces.file = 'Combined_s1_object_3_frontfaces.pgf';
object_3_frontfaces.color = [0.0, 0.0, 0.0];
object_3_frontfaces.opacity = 0.5;
object_3_frontfaces.lighting = true;
object_3_frontfaces.cullface = 'back';
r.add(object_3_frontfaces);

var object_3_faces = new X.mesh();
object_3_faces.children = new Array();
object_3_faces.children.push(object_3_frontfaces);
object_3_faces.children.push(object_3_backfaces);
object_3_faces.color = [0.0, 0.0, 0.0];
object_3_faces.opacity = 0.5;

var object_3 = new X.mesh();
object_3.children = new Array();
object_3.children.push(object_3_wires);
object_3.children.push(object_3_faces);


var object_4_wires = new X.mesh();
object_4_wires.file = 'Combined_s1_object_4_wires.pgf';
object_4_wires.color = [0.0, 0.0, 0.0];
object_4_wires.opacity = 0.5;
object_4_wires.lighting = false;
r.add(object_4_wires);

var object_4_backfaces = new X.mesh();
object_4_backfaces.file = 'Combined_s1_object_4_backfaces.pgf';
object_4_backfaces.color = [1.0, 0.0, 0.0];
object_4_backfaces.opacity = 0.5;
object_4_backfaces.lighting = true;
object_4_backfaces.cullface = 'front';
r.add(object_4_backfaces);

var object_4_frontfaces = new X.mesh();
object_4_frontfaces.file = 'Combined_s1_object_4_frontfaces.pgf';
object_4_frontfaces.color = [1.0, 0.0, 0.0];
object_4_frontfaces.opacity = 0.5;
object_4_frontfaces.lighting = true;
object_4_frontfaces.cullface = 'back';
r.add(object_4_frontfaces);

var object_4_faces = new X.mesh();
object_4_faces.children = new Array();
object_4_faces.children.push(object_4_frontfaces);
object_4_faces.children.push(object_4_backfaces);
object_4_faces.color = [1.0, 0.0, 0.0];
object_4_faces.opacity = 0.5;

var object_4 = new X.mesh();
object_4.children = new Array();
object_4.children.push(object_4_wires);
object_4.children.push(object_4_faces);


var object_5_wires = new X.mesh();
object_5_wires.file = 'Combined_s1_object_5_wires.pgf';
object_5_wires.color = [0.0, 0.0, 0.0];
object_5_wires.opacity = 0.5;
object_5_wires.lighting = false;
r.add(object_5_wires);

var object_5_backfaces = new X.mesh();
object_5_backfaces.file = 'Combined_s1_object_5_backfaces.pgf';
object_5_backfaces.color = [0.0, 1.0, 0.0];
object_5_backfaces.opacity = 0.5;
object_5_backfaces.lighting = true;
object_5_backfaces.cullface = 'front';
r.add(object_5_backfaces);

var object_5_frontfaces = new X.mesh();
object_5_frontfaces.file = 'Combined_s1_object_5_frontfaces.pgf';
object_5_frontfaces.color = [0.0, 1.0, 0.0];
object_5_frontfaces.opacity = 0.5;
object_5_frontfaces.lighting = true;
object_5_frontfaces.cullface = 'back';
r.add(object_5_frontfaces);

var object_5_faces = new X.mesh();
object_5_faces.children = new Array();
object_5_faces.children.push(object_5_frontfaces);
object_5_faces.children.push(object_5_backfaces);
object_5_faces.color = [0.0, 1.0, 0.0];
object_5_faces.opacity = 0.5;

var object_5 = new X.mesh();
object_5.children = new Array();
object_5.children.push(object_5_wires);
object_5.children.push(object_5_faces);


var object_6_wires = new X.mesh();
object_6_wires.file = 'Combined_s1_object_6_wires.pgf';
object_6_wires.color = [0.0, 0.0, 0.0];
object_6_wires.opacity = 0.5;
object_6_wires.lighting = false;
r.add(object_6_wires);

var object_6_backfaces = new X.mesh();
object_6_backfaces.file = 'Combined_s1_object_6_backfaces.pgf';
object_6_backfaces.color = [0.0, 0.0, 1.0];
object_6_backfaces.opacity = 0.5;
object_6_backfaces.lighting = true;
object_6_backfaces.cullface = 'front';
r.add(object_6_backfaces);

var object_6_frontfaces = new X.mesh();
object_6_frontfaces.file = 'Combined_s1_object_6_frontfaces.pgf';
object_6_frontfaces.color = [0.0, 0.0, 1.0];
object_6_frontfaces.opacity = 0.5;
object_6_frontfaces.lighting = true;
object_6_frontfaces.cullface = 'back';
r.add(object_6_frontfaces);

var object_6_faces = new X.mesh();
object_6_faces.children = new Array();
object_6_faces.children.push(object_6_frontfaces);
object_6_faces.children.push(object_6_backfaces);
object_6_faces.color = [0.0, 0.0, 1.0];
object_6_faces.opacity = 0.5;

var object_6 = new X.mesh();
object_6.children = new Array();
object_6.children.push(object_6_wires);
object_6.children.push(object_6_faces);


r.onShowtime = function() {
var gui = new dat.GUI();
the_controls = gui;
var gui_object_3 = gui.addFolder('object_3');
var gui_object_3_visible = gui_object_3.add(object_3,'visible').name('visible');
var gui_object_3_faceopacity = gui_object_3.add(object_3_faces,'opacity',0,1).name('face opacity');
var gui_object_3_facecolor = gui_object_3.addColor(object_3_faces,'color').name('face color');
var gui_object_3_showwires = gui_object_3.add(object_3_wires,'visible').name('show wires');
var gui_object_3_wireopacity = gui_object_3.add(object_3_wires,'opacity',0,1).name('wire opacity');
var gui_object_3_wirecolor = gui_object_3.addColor(object_3_wires,'color').name('wire color');
var gui_object_4 = gui.addFolder('object_4');
var gui_object_4_visible = gui_object_4.add(object_4,'visible').name('visible');
var gui_object_4_faceopacity = gui_object_4.add(object_4_faces,'opacity',0,1).name('face opacity');
var gui_object_4_facecolor = gui_object_4.addColor(object_4_faces,'color').name('face color');
var gui_object_4_showwires = gui_object_4.add(object_4_wires,'visible').name('show wires');
var gui_object_4_wireopacity = gui_object_4.add(object_4_wires,'opacity',0,1).name('wire opacity');
var gui_object_4_wirecolor = gui_object_4.addColor(object_4_wires,'color').name('wire color');
var gui_object_5 = gui.addFolder('object_5');
var gui_object_5_visible = gui_object_5.add(object_5,'visible').name('visible');
var gui_object_5_faceopacity = gui_object_5.add(object_5_faces,'opacity',0,1).name('face opacity');
var gui_object_5_facecolor = gui_object_5.addColor(object_5_faces,'color').name('face color');
var gui_object_5_showwires = gui_object_5.add(object_5_wires,'visible').name('show wires');
var gui_object_5_wireopacity = gui_object_5.add(object_5_wires,'opacity',0,1).name('wire opacity');
var gui_object_5_wirecolor = gui_object_5.addColor(object_5_wires,'color').name('wire color');
var gui_object_6 = gui.addFolder('object_6');
var gui_object_6_visible = gui_object_6.add(object_6,'visible').name('visible');
var gui_object_6_faceopacity = gui_object_6.add(object_6_faces,'opacity',0,1).name('face opacity');
var gui_object_6_facecolor = gui_object_6.addColor(object_6_faces,'color').name('face color');
var gui_object_6_showwires = gui_object_6.add(object_6_wires,'visible').name('show wires');
var gui_object_6_wireopacity = gui_object_6.add(object_6_wires,'opacity',0,1).name('wire opacity');
var gui_object_6_wirecolor = gui_object_6.addColor(object_6_wires,'color').name('wire color');

var gui_camera = gui.addFolder('Camera');
var gui_camera_reset = gui_camera.add(r.camera,'reset');

var gui_global = gui.addFolder('Global');
var gui_global_alphablend = gui_global.add(r,'toggleAlphablend');
}

r.camera.position = [42.0, -57.911231234996166, 26.249999999999986];
r.camera.focus = [42.0, 18.0, 26.25];
r.camera.up = [0.0, -1.8369701e-16, 1.0];

r.render();
};

showSweep = function() {
if (the_controls != null) the_controls.destroy();
if (the_renderer != null) the_renderer.destroy();
var r = new X.renderer3D();
the_renderer = r;
r.config.ORDERING_COMPARATOR = 'ID';
r.init();

r.setAlphablend(false);
var object_11_wires = new X.mesh();
object_11_wires.file = 'Combined_s2_object_11_wires.pgf';
object_11_wires.color = [0.0, 0.0, 0.0];
object_11_wires.opacity = 0.5;
object_11_wires.lighting = false;
r.add(object_11_wires);

var object_11_backfaces = new X.mesh();
object_11_backfaces.file = 'Combined_s2_object_11_backfaces.pgf';
object_11_backfaces.color = [0.0, 1.0, 1.0];
object_11_backfaces.opacity = 0.5;
object_11_backfaces.lighting = true;
object_11_backfaces.cullface = 'front';
r.add(object_11_backfaces);

var object_11_frontfaces = new X.mesh();
object_11_frontfaces.file = 'Combined_s2_object_11_frontfaces.pgf';
object_11_frontfaces.color = [1.0, 0.0, 0.0];
object_11_frontfaces.opacity = 0.5;
object_11_frontfaces.lighting = true;
object_11_frontfaces.cullface = 'back';
r.add(object_11_frontfaces);

var object_11_faces = new X.mesh();
object_11_faces.children = new Array();
object_11_faces.children.push(object_11_frontfaces);
object_11_faces.children.push(object_11_backfaces);
object_11_faces.color = [1.0, 0.0, 0.0];
object_11_faces.opacity = 0.5;

var object_11 = new X.mesh();
object_11.children = new Array();
object_11.children.push(object_11_wires);
object_11.children.push(object_11_faces);


r.onShowtime = function() {
var gui = new dat.GUI();
the_controls = gui;
var gui_object_11 = gui.addFolder('object_11');
var gui_object_11_visible = gui_object_11.add(object_11,'visible').name('visible');
var gui_object_11_faceopacity = gui_object_11.add(object_11_faces,'opacity',0,1).name('face opacity');
var gui_object_11_facecolor = gui_object_11.addColor(object_11_faces,'color').name('face color');
var gui_object_11_showwires = gui_object_11.add(object_11_wires,'visible').name('show wires');
var gui_object_11_wireopacity = gui_object_11.add(object_11_wires,'opacity',0,1).name('wire opacity');
var gui_object_11_wirecolor = gui_object_11.addColor(object_11_wires,'color').name('wire color');

var gui_camera = gui.addFolder('Camera');
var gui_camera_reset = gui_camera.add(r.camera,'reset');

var gui_global = gui.addFolder('Global');
var gui_global_alphablend = gui_global.add(r,'toggleAlphablend');
}

r.camera.position = [-0.67201614379882812, -22.284463630115312, 4.9282650947570756];
r.camera.focus = [-0.67201614, 0.78591251, 4.9282651];
r.camera.up = [0.0, -1.8369701e-16, 1.0];

r.render();
};
